version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command:
            pip install -r requirements.txt
      - run:
          name: Run Unit Test
          command:
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_tests:
    jobs:
      - run_tests